### ISSUE TITLE
Missing migrations after install

### ISSUE THREAD

**Issue by ayushin** [djangoflow/django-df-notifications#1]
```
Running migrations:
  No migrations to apply.
  Your models in app(s): 'df_notifications' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
django@django-web-5c84cd796-vnb7b:/app$ ./manage.py makemigrations
Migrations for 'df_notifications':
  /usr/local/lib/python3.9/site-packages/df_notifications/migrations/0002_alter_notificationhistory_id_alter_userdevice_user.py
    - Alter field id on notificationhistory
    - Alter field user on userdevice
Traceback (most recent call last):
  File "/app/./manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 90, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py", line 190, in handle
    self.write_migration_files(changes)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py", line 228, in write_migration_files
    with open(writer.path, "w", encoding='utf-8') as fh:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.9/site-packages/df_notifications/migrations/0002_alter_notificationhistory_id_alter_userdevice_user.py'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
```

**Comment by eugapx** [comment]
@ayushin Works fine with https://github.com/djangoflow/demo-django, released 0.3
